# Form implementation generated from reading ui file 'D:\K234111362\KTLT\RevisionTDLT\ChuongTrinhInRaCacSoHoanHao\hoanhao.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 40, 691, 461))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(239, 243, 255);")
        self.groupBox.setObjectName("groupBox")
        self.insohoanhao = QtWidgets.QTextEdit(parent=self.groupBox)
        self.insohoanhao.setGeometry(QtCore.QRect(80, 260, 531, 161))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.insohoanhao.setFont(font)
        self.insohoanhao.setStyleSheet("background-color: rgb(189, 215, 231);")
        self.insohoanhao.setObjectName("insohoanhao")
        self.timsohoanhao = QtWidgets.QPushButton(parent=self.groupBox)
        self.timsohoanhao.setGeometry(QtCore.QRect(190, 170, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(20)
        self.timsohoanhao.setFont(font)
        self.timsohoanhao.setStyleSheet("background-color: rgb(189, 215, 231);\n"
"background-color: rgb(33, 113, 181);")
        self.timsohoanhao.setObjectName("timsohoanhao")
        self.gioihan = QtWidgets.QLineEdit(parent=self.groupBox)
        self.gioihan.setGeometry(QtCore.QRect(280, 80, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gioihan.setFont(font)
        self.gioihan.setStyleSheet("background-color: rgb(107, 174, 214);")
        self.gioihan.setObjectName("gioihan")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 80, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "CHƯƠNG TRÌNH IN RA CÁC SỐ HOÀN HẢO"))
        self.timsohoanhao.setText(_translate("MainWindow", "Tìm số hoàn hảo"))
        self.label.setText(_translate("MainWindow", "Nhập giới hạn"))
